{% set name = "upoly" %}
{% set version = "0.1.32" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/upoly-{{ version }}.tar.gz
  sha256: c05febcd53d162b1a71515d52dc522e50edf8418b3d065c825d47c97fe3f14f1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<3.9
  run:
    - aiodns >=2.0.0,<3.0.0
    - aiohttp >=3.7.3,<4.0.0
    - brotli >=1.0.9,<2.0.0
    - cchardet >=2.1.7,<3.0.0
    - joblib >=1.0.1,<2.0.0
    - nest-asyncio >=1.4.3,<2.0.0
    - numpy >=1.20.1,<2.0.0
    - orjson >=3.4.6,<4.0.0
    - pandas >=1.2.2,<2.0.0
    - pandas_market_calendars >=1.6.1,<2.0.0
    - python >=3.6,<3.9
    - python-dotenv >=0.15.0,<0.16.0
    - setuptools >=49.0.0,<54.0.0

test:
  imports:
    - upoly
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/upoly/
  summary: High performance asyncio REST client for polygon.io
  license: AGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - riley
